#!/usr/bin/env node

/**
 * commit-msg.cjs
 *
 * MESSAGE ENFORCER
 * Validates commit message format: task-ID required, summary line length, body structure
 * Fires before commit is finalized (last chance to reject invalid messages)
 *
 * Why this matters:
 * Every commit must be trackable to a task. Without task-ID in message,
 * brain/inbox can't correlate commits to tasks, dreamer can't score decisions,
 * and cross-project tracking breaks. This is the last defense.
 *
 * Cannot be bypassed:
 * - Rationalization: "Task ID is optional for cleanup commits"
 *   Truth: EVERYTHING needs tracking. Cleanup is a task with a task-ID.
 * - Rationalization: "I'll add it manually later"
 *   Truth: You won't. Message once, stored forever.
 *
 * Usage:
 *   Installed via forge-install-hooks in tracked projects
 *   node commit-msg.cjs <commit-msg-file>
 *
 * Exit codes:
 *   0 = message valid (commit allowed)
 *   1 = message invalid (commit rejected)
 *
 * Cross-platform: works on Linux, macOS, Windows
 */

const fs = require('fs');

const COMMIT_MSG_FILE = process.argv[2];

function die(message) {
  console.error(`\n❌ COMMIT MESSAGE REJECTED: ${message}`);
  console.error('\nCommit message format required:');
  console.error('  task-NNN: Brief summary (< 72 chars)');
  console.error('  ');
  console.error('  Optional detailed explanation here.');
  console.error('');
  process.exit(1);
}

function allow() {
  process.exit(0);
}

// ==================== Edge Cases & Fallback Paths ====================
// Edge Case 1: Merge commit (auto-generated by git)
//   Action: Allow merge commits (format controlled by git, not user)
//   Escalation: None - merge commits are auto-formatted
//
// Edge Case 2: Revert commit (should preserve original task-ID)
//   Action: Allow if "Revert" format is followed
//   Escalation: None - revert format is standard
//
// Edge Case 3: Release/version commit (special format like "v1.2.3: release notes")
//   Action: Allow if starts with 'v' or 'release'
//   Escalation: None - version commits have different format
//
// Edge Case 4: Empty commit message
//   Action: Reject - requires at least a summary line
//   Escalation: User must provide meaningful message
//
// Edge Case 5: Message with only whitespace
//   Action: Reject - empty message after trim
//   Escalation: User must provide message
//
// Edge Case 6: Message too long (> 100 chars summary line)
//   Action: Reject - enforces readability
//   Escalation: User shortens message or moves detail to body
// ==================== End Edge Case Definitions ====================

function log(message) {
  const timestamp = new Date().toISOString().split('T')[1].split('.')[0];
  console.error(`[${timestamp}] ${message}`);
}

// Validate file exists
if (!COMMIT_MSG_FILE || !fs.existsSync(COMMIT_MSG_FILE)) {
  die(`Commit message file not provided or not found: ${COMMIT_MSG_FILE}`);
}

// Read commit message
let message = '';
try {
  message = fs.readFileSync(COMMIT_MSG_FILE, 'utf-8');
} catch (e) {
  die(`Cannot read commit message file: ${e.message}`);
}

// Trim and check for empty
const trimmed = message.trim();
if (!trimmed) {
  die('Commit message cannot be empty');
}

// Split into lines
const lines = trimmed.split('\n');
const firstLine = lines[0];
const secondLine = lines.length > 1 ? lines[1] : '';

// Edge case: merge commit (auto-generated by git)
if (firstLine.startsWith('Merge ')) {
  log('Merge commit detected - format auto-generated, allowing');
  allow();
}

// Edge case: revert commit (format: Revert "original message")
if (firstLine.startsWith('Revert ')) {
  log('Revert commit detected - standard format, allowing');
  allow();
}

// Edge case: release/version commit (v1.2.3, release:, etc.)
if (/^(v\d+\.\d+\.\d+|release:|RELEASE:|version:)/i.test(firstLine)) {
  log('Version/release commit detected - special format allowed');
  allow();
}

// Edge case: conventional commits (feat:, fix:, docs:, chore:, refactor:, test:, etc.)
// The forge repo itself uses conventional commits; tracked projects may also prefer this.
const conventionalCommitPattern = /^(feat|fix|docs|chore|refactor|test|style|perf|ci|build|revert)(\(.+\))?!?:\s+\S+/i;
const isConventional = conventionalCommitPattern.test(firstLine);

// Validate first line has task-ID (format: task-NNN or task-NNNN)
// Allow formats: task-123, TASK-123, [task-123], (task-123)
const taskIdPattern = /task-[\w-]+/i;
if (!taskIdPattern.test(firstLine) && !isConventional) {
  die(
    `Summary line missing task-ID or conventional commit prefix.\n` +
    `  Found: "${firstLine}"\n` +
    `  Accepted formats:\n` +
    `    task-NNN: summary  (e.g., "task-123: fix login bug")\n` +
    `    feat: summary      (e.g., "feat: add 2fa support")\n` +
    `    fix(scope): summary`
  );
}

// Validate summary line length (< 100 chars is reasonable, < 72 is ideal)
if (firstLine.length > 100) {
  die(
    `Summary line too long (${firstLine.length} chars, max 100).\n` +
    `  Preferred: < 72 chars\n` +
    `  Found: "${firstLine}"`
  );
}

// Validate summary line has meaningful text after task-ID
// Pattern: task-NNN: [something meaningful]
const summaryPattern = /^task-[\w-]+:\s+\S+/i;
if (!summaryPattern.test(firstLine) && !isConventional) {
  die(
    `Summary line must have text after task-ID.\n` +
    `  Format: "task-NNN: summary text" (e.g., "task-123: fix login bug")\n` +
    `  Found: "${firstLine}"`
  );
}

// Validate second line (if present) is blank (conventional format)
if (lines.length > 1 && secondLine.trim() !== '') {
  die(
    `Line 2 must be blank (conventional format).\n` +
    `  Found: "${secondLine}"\n` +
    `  Fix: Add blank line between summary and body`
  );
}

log(`Commit message valid: "${firstLine.substring(0, 60)}..."`);
allow();
